version: 0.2

env:
  variables:
    JAR_NAME: movie-app-0.0.1-SNAPSHOT.jar
    EC2_HOST: ec2-43-204-108-0.ap-south-1.compute.amazonaws.com
    EC2_USER: ubuntu
    REMOTE_DIR: /home/ubuntu
    KEY_PATH: github-action-key.pem

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo "🏗️ Building Spring Boot JAR using Maven..."
      - ./mvnw clean package -DskipTests

      - echo "🔐 Setting permissions for SSH key..."
      - chmod 400 $KEY_PATH

      - echo "📤 Uploading JAR to EC2..."
      - scp -i "$KEY_PATH" "target/$JAR_NAME" $EC2_USER@$EC2_HOST:$REMOTE_DIR/

      - echo "🚀 Restarting app on EC2..."
      - ssh -i "$KEY_PATH" $EC2_USER@$EC2_HOST \
        "mkdir -p $REMOTE_DIR/logs && \
        pkill -f $JAR_NAME || true && \
        nohup java -jar $REMOTE_DIR/$JAR_NAME > $REMOTE_DIR/logs/movie-app.log 2>&1 & \
        echo '✅ App restarted with nohup'"