spring:
  datasource:
    url: jdbc:postgres://ec2-52-86-73-86.compute-1.amazonaws.com:5432/d5lmhq6fu5pejc
    username: hjhsjdulzdcstk
    password: b1a8f63287b59dcdf655531661fb54ed6f5e2553cec332fbe83e2fffc7d86acd
    driver: org.postgresql.Driver

  mybatis:
    type-aliases-package: com.om.movieapp.model
    mapper-locations: classpath:/mapper/*xml




